### ISSUE TITLE
Checklist Week 12 - Active community building

### ISSUE THREAD

**Issue by thessaly** [Open-Hardware-Leaders/curriculum#13]
**Goal of the week**
  Expose actively your work to individuals and groups that could contribute to your project

**Assignments**

- [ ] Search for available platforms, groups or communities that are related to your project.
- [ ] Expose your work there, for instance by creating a page/profile for your project on platforms like wikifactory or hackaday.
- [ ] Identify people in these platforms and communities that can be interested in your project directly and introduce them to your projects.
