### ISSUE TITLE
Checklist Week 3

### ISSUE THREAD

**Issue by thessaly** [Open-Hardware-Leaders/curriculum#4]
**Goal of the week:**
Learn to design and frame experiments to validate key hypothesis in your project

**Assignments:**

- [ ] Watch [video tutorial](https://openhardware4.me/open-hardware-leaders.github.io/Program/10_Week3.html) on how to make test cards with github issues

- [ ] Extract 6 key hypothesis/assumptions that are related to your core value proposition

- [ ] Design experiments (tasks) that tackle those specific hypotheses, goals, targets

- [ ] Consider which resources do you need to achieve them. Which resources do you already have at hand? How can your mentor help you in getting those resources you need?

- [ ] Open issues that describe the experiments you designed and use the project board in GitHub to reflect which actions you will take.

If you have new hypothesis and ideas on user and contributor profiles update your canvas. What would you do to validate these ideas, what experiments would you design?
