### ISSUE TITLE
Checklist Week 5

### ISSUE THREAD

**Issue by thessaly** [Open-Hardware-Leaders/curriculum#6]
**Goal of the week**

- Learn to prioritize and scope releases
- Plan and start running a sprint based on your defined priorities

**Assignments**

- [ ] Define the scope statement for your participation in the program
- [ ] Prioritize your work based on feasibility and relevance, using the github project board
- [ ] Decompose your test cards in achievable activities in a timeline (or tasks)
- [ ] Move these tasks into the sprint backlog planning.

If you have new hypothesis and ideas update your canvas. What would you do to validate these ideas, what experiments would you design?
