### ISSUE TITLE
Checklist Week 6

### ISSUE THREAD

**Issue by thessaly** [Open-Hardware-Leaders/curriculum#7]
**Goal of the week:** 
Create entry points for contributors and users (Contributor User channels)/ Websites, issues, repositories, labels, code of conduct.

**Assignments:**

- [ ] Create issues for contributors to jump into your project
- [ ] Write your contribution guidelines
- [ ] Think of strategies for engaging and including wider audiences, and define your community guidelines (or code of conduct).

If you have new hypothesis and ideas update your canvas. What would you do to validate these ideas, what experiments would you design?
