### ISSUE TITLE
Checklist Week 7

### ISSUE THREAD

**Issue by thessaly** [Open-Hardware-Leaders/curriculum#8]
**Goals of the week**

Understand different experiences in open source governance and management models

**Assignments**

- [ ]    Watch [this week’s video](https://openhardware4.me/Program/14_Week7.html)
- [ ]    See at least one of the videos we have compiled for you in the slides
- [ ]    Share your insights, reflections and questions in [this issue](https://github.com/Open-Hardware-Leaders/ohlwebsite/issues/6)
